version: '3'

services:

  redis:
    image: redis:latest
    ports:
      - "6379:6349"

  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - '5433:5432'
    environment:
      - PGDATA=/var/lib/postgresql/data/pg_db
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pg_data:/var/lib/postgresql/data/pg_db
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -d $${DATABASE_NAME} -U $${DATABASE_USER}' ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    tty: true
    command: python3 manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  celery:
    build: .
    tty: true
    command: celery -A config worker -l INFO
    depends_on:
      - redis
      - app

  celery_beat:
    build: .
    tty: true
    command: celery -A config bear -l INFO -S django
    depends_on:
      - redis
      - app

volumes:
  pg_data: